### ISSUE TITLE
error in docstrings

### ISSUE THREAD

**Issue by dragoncoder047** [technoblogy/ulisp-esp#59]
The docstring for `log` doesn't include `log` (it just starts with `(number [base])`)

Should be `(log number [base])`.

**Comment by dragoncoder047** [comment]
The docstrings for `truncate` and `round` also have the docstring of `floatp` by mistake. What should they be?

**Comment by dragoncoder047** [comment]
* `lognot` has the entire docstring of `prin1-to-string`

**Comment by technoblogy** [comment]
Thanks for spotting these. Will fix.

> The docstrings for truncate and round also have the docstring of floatp by mistake. What should they be?

    "(truncate number [divisor])\n"
    "Returns the integer part of number/divisor. If divisor is omitted it defaults to 1."

    "(round number [divisor])\n"
    "Returns the integer closest to number/divisor. If divisor is omitted it defaults to 1."

(from [Floating-point extensions](http://www.ulisp.com/show?1G5Y)).

**Comment by technoblogy** [comment]
PS When did this emoji menu appear in GitHub issues? I kept thinking I'd typed in a smiley by mistake.

**Comment by technoblogy** [comment]
Fixed in 4.4b - thanks!
