### ISSUE TITLE
`(read-line)` processes backslash escapes when it shouldn't (it uses readstring())

### ISSUE THREAD

**Issue by dragoncoder047** [technoblogy/ulisp-esp#67]
```
> (read-line)
foo \
bar
"foo
bar"
> (read-line)
foo \bar
"foo bar"
```

Common Lisp does not do this:

```
CL-USER> (defvar s "foo \\
bar")
"foo \\
bar"
CL-USER> (defvar st (make-string-input-stream s))
#<INPUT STRING-INPUT-STREAM>
CL-USER> (princ (read-line st))
foo \
"foo \\"
```

I think the intention of `(read-line)` was to ignore backslashes and include them.

**Comment by technoblogy** [comment]
Good point - thanks.

**Comment by dragoncoder047** [comment]
I think an easy solution would be to have a third parameter `doEscape` and pass true in `(read)` and false in `(read-line)`.

**Comment by technoblogy** [comment]
Yes, I was thinking along the same lines.

**Comment by dragoncoder047** [comment]
It just dawned on me that you could implement something like `(make-string-input-stream)` / `(with-input-from-string)` by simply using `gstr()`. Unfortunately until #64 is resolved it will only work for one stringstream, but that's already an inherent limitation with the current implementation.

**Comment by technoblogy** [comment]
Good point. I've already got **with-output-to-string** so I don't know why I didn't include **with-input-from-string**.
